// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  Address,
  DataSourceTemplate,
  DataSourceContext
} from "@graphprotocol/graph-ts";

export class NFTCollateralVault extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("NFTCollateralVault", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "NFTCollateralVault",
      [address.toHex()],
      context
    );
  }
}

export class Fragment extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("Fragment", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "Fragment",
      [address.toHex()],
      context
    );
  }
}
