// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class OrderHistory extends ethereum.Event {
  get params(): OrderHistory__Params {
    return new OrderHistory__Params(this);
  }
}

export class OrderHistory__Params {
  _event: OrderHistory;

  constructor(event: OrderHistory) {
    this._event = event;
  }

  get fromToken(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get toToken(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get sender(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get fromAmount(): BigInt {
    return this._event.parameters[3].value.toBigInt();
  }

  get returnAmount(): BigInt {
    return this._event.parameters[4].value.toBigInt();
  }
}

export class DODORouteProxy extends ethereum.SmartContract {
  static bind(address: Address): DODORouteProxy {
    return new DODORouteProxy("DODORouteProxy", address);
  }

  _DODO_APPROVE_PROXY_(): Address {
    let result = super.call(
      "_DODO_APPROVE_PROXY_",
      "_DODO_APPROVE_PROXY_():(address)",
      []
    );

    return result[0].toAddress();
  }

  try__DODO_APPROVE_PROXY_(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "_DODO_APPROVE_PROXY_",
      "_DODO_APPROVE_PROXY_():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  _WETH_(): Address {
    let result = super.call("_WETH_", "_WETH_():(address)", []);

    return result[0].toAddress();
  }

  try__WETH_(): ethereum.CallResult<Address> {
    let result = super.tryCall("_WETH_", "_WETH_():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }

  get weth(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get dodoApproveProxy(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class DefaultCall extends ethereum.Call {
  get inputs(): DefaultCall__Inputs {
    return new DefaultCall__Inputs(this);
  }

  get outputs(): DefaultCall__Outputs {
    return new DefaultCall__Outputs(this);
  }
}

export class DefaultCall__Inputs {
  _call: DefaultCall;

  constructor(call: DefaultCall) {
    this._call = call;
  }
}

export class DefaultCall__Outputs {
  _call: DefaultCall;

  constructor(call: DefaultCall) {
    this._call = call;
  }
}

export class DodoMutliSwapCall extends ethereum.Call {
  get inputs(): DodoMutliSwapCall__Inputs {
    return new DodoMutliSwapCall__Inputs(this);
  }

  get outputs(): DodoMutliSwapCall__Outputs {
    return new DodoMutliSwapCall__Outputs(this);
  }
}

export class DodoMutliSwapCall__Inputs {
  _call: DodoMutliSwapCall;

  constructor(call: DodoMutliSwapCall) {
    this._call = call;
  }

  get fromTokenAmount(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }

  get minReturnAmount(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }

  get totalWeight(): Array<BigInt> {
    return this._call.inputValues[2].value.toBigIntArray();
  }

  get splitNumber(): Array<BigInt> {
    return this._call.inputValues[3].value.toBigIntArray();
  }

  get midToken(): Array<Address> {
    return this._call.inputValues[4].value.toAddressArray();
  }

  get assetFrom(): Array<Address> {
    return this._call.inputValues[5].value.toAddressArray();
  }

  get sequence(): Array<Bytes> {
    return this._call.inputValues[6].value.toBytesArray();
  }

  get deadLine(): BigInt {
    return this._call.inputValues[7].value.toBigInt();
  }
}

export class DodoMutliSwapCall__Outputs {
  _call: DodoMutliSwapCall;

  constructor(call: DodoMutliSwapCall) {
    this._call = call;
  }

  get returnAmount(): BigInt {
    return this._call.outputValues[0].value.toBigInt();
  }
}
