// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  TypedMap,
  Entity,
  Value,
  ValueKind,
  store,
  Address,
  Bytes,
  BigInt,
  BigDecimal
} from "@graphprotocol/graph-ts";

export class User extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save User entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save User entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("User", id.toString(), this);
  }

  static load(id: string): User | null {
    return store.get("User", id) as User | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get usdcSwapped(): BigDecimal {
    let value = this.get("usdcSwapped");
    return value.toBigDecimal();
  }

  set usdcSwapped(value: BigDecimal) {
    this.set("usdcSwapped", Value.fromBigDecimal(value));
  }

  get txCount(): BigInt {
    let value = this.get("txCount");
    return value.toBigInt();
  }

  set txCount(value: BigInt) {
    this.set("txCount", Value.fromBigInt(value));
  }

  get tradingRewardRecieved(): BigDecimal {
    let value = this.get("tradingRewardRecieved");
    return value.toBigDecimal();
  }

  set tradingRewardRecieved(value: BigDecimal) {
    this.set("tradingRewardRecieved", Value.fromBigDecimal(value));
  }

  get liquidityPositions(): Array<string> | null {
    let value = this.get("liquidityPositions");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set liquidityPositions(value: Array<string> | null) {
    if (value === null) {
      this.unset("liquidityPositions");
    } else {
      this.set(
        "liquidityPositions",
        Value.fromStringArray(value as Array<string>)
      );
    }
  }
}

export class LiquidityPosition extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save LiquidityPosition entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save LiquidityPosition entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("LiquidityPosition", id.toString(), this);
  }

  static load(id: string): LiquidityPosition | null {
    return store.get("LiquidityPosition", id) as LiquidityPosition | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get user(): string {
    let value = this.get("user");
    return value.toString();
  }

  set user(value: string) {
    this.set("user", Value.fromString(value));
  }

  get pair(): string {
    let value = this.get("pair");
    return value.toString();
  }

  set pair(value: string) {
    this.set("pair", Value.fromString(value));
  }

  get liquidityTokenBalance(): BigDecimal {
    let value = this.get("liquidityTokenBalance");
    return value.toBigDecimal();
  }

  set liquidityTokenBalance(value: BigDecimal) {
    this.set("liquidityTokenBalance", Value.fromBigDecimal(value));
  }
}

export class Token extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Token entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Token entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Token", id.toString(), this);
  }

  static load(id: string): Token | null {
    return store.get("Token", id) as Token | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get symbol(): string {
    let value = this.get("symbol");
    return value.toString();
  }

  set symbol(value: string) {
    this.set("symbol", Value.fromString(value));
  }

  get name(): string {
    let value = this.get("name");
    return value.toString();
  }

  set name(value: string) {
    this.set("name", Value.fromString(value));
  }

  get decimals(): BigInt {
    let value = this.get("decimals");
    return value.toBigInt();
  }

  set decimals(value: BigInt) {
    this.set("decimals", Value.fromBigInt(value));
  }

  get totalSupply(): BigInt {
    let value = this.get("totalSupply");
    return value.toBigInt();
  }

  set totalSupply(value: BigInt) {
    this.set("totalSupply", Value.fromBigInt(value));
  }

  get tradeVolume(): BigDecimal {
    let value = this.get("tradeVolume");
    return value.toBigDecimal();
  }

  set tradeVolume(value: BigDecimal) {
    this.set("tradeVolume", Value.fromBigDecimal(value));
  }

  get tradeVolumeUSDC(): BigDecimal {
    let value = this.get("tradeVolumeUSDC");
    return value.toBigDecimal();
  }

  set tradeVolumeUSDC(value: BigDecimal) {
    this.set("tradeVolumeUSDC", Value.fromBigDecimal(value));
  }

  get txCount(): BigInt {
    let value = this.get("txCount");
    return value.toBigInt();
  }

  set txCount(value: BigInt) {
    this.set("txCount", Value.fromBigInt(value));
  }

  get totalLiquidityOnDODO(): BigDecimal {
    let value = this.get("totalLiquidityOnDODO");
    return value.toBigDecimal();
  }

  set totalLiquidityOnDODO(value: BigDecimal) {
    this.set("totalLiquidityOnDODO", Value.fromBigDecimal(value));
  }

  get priceUSDC(): BigDecimal {
    let value = this.get("priceUSDC");
    return value.toBigDecimal();
  }

  set priceUSDC(value: BigDecimal) {
    this.set("priceUSDC", Value.fromBigDecimal(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }
}

export class LpToken extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save LpToken entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save LpToken entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("LpToken", id.toString(), this);
  }

  static load(id: string): LpToken | null {
    return store.get("LpToken", id) as LpToken | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get symbol(): string {
    let value = this.get("symbol");
    return value.toString();
  }

  set symbol(value: string) {
    this.set("symbol", Value.fromString(value));
  }

  get name(): string {
    let value = this.get("name");
    return value.toString();
  }

  set name(value: string) {
    this.set("name", Value.fromString(value));
  }

  get decimals(): BigInt {
    let value = this.get("decimals");
    return value.toBigInt();
  }

  set decimals(value: BigInt) {
    this.set("decimals", Value.fromBigInt(value));
  }

  get totalSupply(): BigInt {
    let value = this.get("totalSupply");
    return value.toBigInt();
  }

  set totalSupply(value: BigInt) {
    this.set("totalSupply", Value.fromBigInt(value));
  }
}

export class OrderHistory extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save OrderHistory entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save OrderHistory entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("OrderHistory", id.toString(), this);
  }

  static load(id: string): OrderHistory | null {
    return store.get("OrderHistory", id) as OrderHistory | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get hash(): string {
    let value = this.get("hash");
    return value.toString();
  }

  set hash(value: string) {
    this.set("hash", Value.fromString(value));
  }

  get block(): BigInt {
    let value = this.get("block");
    return value.toBigInt();
  }

  set block(value: BigInt) {
    this.set("block", Value.fromBigInt(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }

  get sender(): Bytes {
    let value = this.get("sender");
    return value.toBytes();
  }

  set sender(value: Bytes) {
    this.set("sender", Value.fromBytes(value));
  }

  get from(): Bytes {
    let value = this.get("from");
    return value.toBytes();
  }

  set from(value: Bytes) {
    this.set("from", Value.fromBytes(value));
  }

  get fromToken(): string {
    let value = this.get("fromToken");
    return value.toString();
  }

  set fromToken(value: string) {
    this.set("fromToken", Value.fromString(value));
  }

  get toToken(): string {
    let value = this.get("toToken");
    return value.toString();
  }

  set toToken(value: string) {
    this.set("toToken", Value.fromString(value));
  }

  get to(): Bytes {
    let value = this.get("to");
    return value.toBytes();
  }

  set to(value: Bytes) {
    this.set("to", Value.fromBytes(value));
  }

  get logIndex(): BigInt | null {
    let value = this.get("logIndex");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set logIndex(value: BigInt | null) {
    if (value === null) {
      this.unset("logIndex");
    } else {
      this.set("logIndex", Value.fromBigInt(value as BigInt));
    }
  }

  get amountIn(): BigDecimal {
    let value = this.get("amountIn");
    return value.toBigDecimal();
  }

  set amountIn(value: BigDecimal) {
    this.set("amountIn", Value.fromBigDecimal(value));
  }

  get amountOut(): BigDecimal {
    let value = this.get("amountOut");
    return value.toBigDecimal();
  }

  set amountOut(value: BigDecimal) {
    this.set("amountOut", Value.fromBigDecimal(value));
  }

  get amountUSDC(): BigDecimal {
    let value = this.get("amountUSDC");
    return value.toBigDecimal();
  }

  set amountUSDC(value: BigDecimal) {
    this.set("amountUSDC", Value.fromBigDecimal(value));
  }
}

export class LiquidityHistory extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save LiquidityHistory entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save LiquidityHistory entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("LiquidityHistory", id.toString(), this);
  }

  static load(id: string): LiquidityHistory | null {
    return store.get("LiquidityHistory", id) as LiquidityHistory | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get hash(): string {
    let value = this.get("hash");
    return value.toString();
  }

  set hash(value: string) {
    this.set("hash", Value.fromString(value));
  }

  get block(): BigInt {
    let value = this.get("block");
    return value.toBigInt();
  }

  set block(value: BigInt) {
    this.set("block", Value.fromBigInt(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }

  get user(): string {
    let value = this.get("user");
    return value.toString();
  }

  set user(value: string) {
    this.set("user", Value.fromString(value));
  }

  get from(): Bytes {
    let value = this.get("from");
    return value.toBytes();
  }

  set from(value: Bytes) {
    this.set("from", Value.fromBytes(value));
  }

  get amount(): BigDecimal {
    let value = this.get("amount");
    return value.toBigDecimal();
  }

  set amount(value: BigDecimal) {
    this.set("amount", Value.fromBigDecimal(value));
  }

  get balance(): BigDecimal {
    let value = this.get("balance");
    return value.toBigDecimal();
  }

  set balance(value: BigDecimal) {
    this.set("balance", Value.fromBigDecimal(value));
  }

  get pair(): string {
    let value = this.get("pair");
    return value.toString();
  }

  set pair(value: string) {
    this.set("pair", Value.fromString(value));
  }

  get baseReserve(): BigDecimal | null {
    let value = this.get("baseReserve");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigDecimal();
    }
  }

  set baseReserve(value: BigDecimal | null) {
    if (value === null) {
      this.unset("baseReserve");
    } else {
      this.set("baseReserve", Value.fromBigDecimal(value as BigDecimal));
    }
  }

  get quoteReserve(): BigDecimal | null {
    let value = this.get("quoteReserve");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigDecimal();
    }
  }

  set quoteReserve(value: BigDecimal | null) {
    if (value === null) {
      this.unset("quoteReserve");
    } else {
      this.set("quoteReserve", Value.fromBigDecimal(value as BigDecimal));
    }
  }

  get lpTokenTotalSupply(): BigDecimal | null {
    let value = this.get("lpTokenTotalSupply");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigDecimal();
    }
  }

  set lpTokenTotalSupply(value: BigDecimal | null) {
    if (value === null) {
      this.unset("lpTokenTotalSupply");
    } else {
      this.set("lpTokenTotalSupply", Value.fromBigDecimal(value as BigDecimal));
    }
  }

  get baseTokenPrice(): BigDecimal | null {
    let value = this.get("baseTokenPrice");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigDecimal();
    }
  }

  set baseTokenPrice(value: BigDecimal | null) {
    if (value === null) {
      this.unset("baseTokenPrice");
    } else {
      this.set("baseTokenPrice", Value.fromBigDecimal(value as BigDecimal));
    }
  }

  get quoteTokenPrice(): BigDecimal | null {
    let value = this.get("quoteTokenPrice");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigDecimal();
    }
  }

  set quoteTokenPrice(value: BigDecimal | null) {
    if (value === null) {
      this.unset("quoteTokenPrice");
    } else {
      this.set("quoteTokenPrice", Value.fromBigDecimal(value as BigDecimal));
    }
  }
}

export class Pair extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Pair entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Pair entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Pair", id.toString(), this);
  }

  static load(id: string): Pair | null {
    return store.get("Pair", id) as Pair | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get type(): string {
    let value = this.get("type");
    return value.toString();
  }

  set type(value: string) {
    this.set("type", Value.fromString(value));
  }

  get creator(): Bytes {
    let value = this.get("creator");
    return value.toBytes();
  }

  set creator(value: Bytes) {
    this.set("creator", Value.fromBytes(value));
  }

  get baseToken(): string {
    let value = this.get("baseToken");
    return value.toString();
  }

  set baseToken(value: string) {
    this.set("baseToken", Value.fromString(value));
  }

  get quoteToken(): string {
    let value = this.get("quoteToken");
    return value.toString();
  }

  set quoteToken(value: string) {
    this.set("quoteToken", Value.fromString(value));
  }

  get i(): BigInt | null {
    let value = this.get("i");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set i(value: BigInt | null) {
    if (value === null) {
      this.unset("i");
    } else {
      this.set("i", Value.fromBigInt(value as BigInt));
    }
  }

  get k(): BigInt | null {
    let value = this.get("k");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set k(value: BigInt | null) {
    if (value === null) {
      this.unset("k");
    } else {
      this.set("k", Value.fromBigInt(value as BigInt));
    }
  }

  get lpFeeRate(): BigDecimal {
    let value = this.get("lpFeeRate");
    return value.toBigDecimal();
  }

  set lpFeeRate(value: BigDecimal) {
    this.set("lpFeeRate", Value.fromBigDecimal(value));
  }

  get baseLpToken(): string | null {
    let value = this.get("baseLpToken");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set baseLpToken(value: string | null) {
    if (value === null) {
      this.unset("baseLpToken");
    } else {
      this.set("baseLpToken", Value.fromString(value as string));
    }
  }

  get quoteLpToken(): string | null {
    let value = this.get("quoteLpToken");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set quoteLpToken(value: string | null) {
    if (value === null) {
      this.unset("quoteLpToken");
    } else {
      this.set("quoteLpToken", Value.fromString(value as string));
    }
  }

  get baseReserve(): BigDecimal {
    let value = this.get("baseReserve");
    return value.toBigDecimal();
  }

  set baseReserve(value: BigDecimal) {
    this.set("baseReserve", Value.fromBigDecimal(value));
  }

  get quoteReserve(): BigDecimal {
    let value = this.get("quoteReserve");
    return value.toBigDecimal();
  }

  set quoteReserve(value: BigDecimal) {
    this.set("quoteReserve", Value.fromBigDecimal(value));
  }

  get reserveUSDC(): BigDecimal {
    let value = this.get("reserveUSDC");
    return value.toBigDecimal();
  }

  set reserveUSDC(value: BigDecimal) {
    this.set("reserveUSDC", Value.fromBigDecimal(value));
  }

  get volumeBaseToken(): BigDecimal {
    let value = this.get("volumeBaseToken");
    return value.toBigDecimal();
  }

  set volumeBaseToken(value: BigDecimal) {
    this.set("volumeBaseToken", Value.fromBigDecimal(value));
  }

  get volumeQuoteToken(): BigDecimal {
    let value = this.get("volumeQuoteToken");
    return value.toBigDecimal();
  }

  set volumeQuoteToken(value: BigDecimal) {
    this.set("volumeQuoteToken", Value.fromBigDecimal(value));
  }

  get tradeVolumeUSDC(): BigDecimal {
    let value = this.get("tradeVolumeUSDC");
    return value.toBigDecimal();
  }

  set tradeVolumeUSDC(value: BigDecimal) {
    this.set("tradeVolumeUSDC", Value.fromBigDecimal(value));
  }

  get txCount(): BigInt {
    let value = this.get("txCount");
    return value.toBigInt();
  }

  set txCount(value: BigInt) {
    this.set("txCount", Value.fromBigInt(value));
  }

  get createdAtTimestamp(): BigInt {
    let value = this.get("createdAtTimestamp");
    return value.toBigInt();
  }

  set createdAtTimestamp(value: BigInt) {
    this.set("createdAtTimestamp", Value.fromBigInt(value));
  }

  get createdAtBlockNumber(): BigInt {
    let value = this.get("createdAtBlockNumber");
    return value.toBigInt();
  }

  set createdAtBlockNumber(value: BigInt) {
    this.set("createdAtBlockNumber", Value.fromBigInt(value));
  }

  get liquidityProviderCount(): BigInt {
    let value = this.get("liquidityProviderCount");
    return value.toBigInt();
  }

  set liquidityProviderCount(value: BigInt) {
    this.set("liquidityProviderCount", Value.fromBigInt(value));
  }

  get mtFeeRateModel(): Bytes {
    let value = this.get("mtFeeRateModel");
    return value.toBytes();
  }

  set mtFeeRateModel(value: Bytes) {
    this.set("mtFeeRateModel", Value.fromBytes(value));
  }

  get maintainer(): Bytes {
    let value = this.get("maintainer");
    return value.toBytes();
  }

  set maintainer(value: Bytes) {
    this.set("maintainer", Value.fromBytes(value));
  }
}

export class Swap extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Swap entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Swap entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Swap", id.toString(), this);
  }

  static load(id: string): Swap | null {
    return store.get("Swap", id) as Swap | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get hash(): string {
    let value = this.get("hash");
    return value.toString();
  }

  set hash(value: string) {
    this.set("hash", Value.fromString(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }

  get pair(): string {
    let value = this.get("pair");
    return value.toString();
  }

  set pair(value: string) {
    this.set("pair", Value.fromString(value));
  }

  get sender(): Bytes {
    let value = this.get("sender");
    return value.toBytes();
  }

  set sender(value: Bytes) {
    this.set("sender", Value.fromBytes(value));
  }

  get from(): Bytes {
    let value = this.get("from");
    return value.toBytes();
  }

  set from(value: Bytes) {
    this.set("from", Value.fromBytes(value));
  }

  get fromToken(): string {
    let value = this.get("fromToken");
    return value.toString();
  }

  set fromToken(value: string) {
    this.set("fromToken", Value.fromString(value));
  }

  get toToken(): string {
    let value = this.get("toToken");
    return value.toString();
  }

  set toToken(value: string) {
    this.set("toToken", Value.fromString(value));
  }

  get to(): Bytes {
    let value = this.get("to");
    return value.toBytes();
  }

  set to(value: Bytes) {
    this.set("to", Value.fromBytes(value));
  }

  get logIndex(): BigInt {
    let value = this.get("logIndex");
    return value.toBigInt();
  }

  set logIndex(value: BigInt) {
    this.set("logIndex", Value.fromBigInt(value));
  }

  get amountIn(): BigDecimal {
    let value = this.get("amountIn");
    return value.toBigDecimal();
  }

  set amountIn(value: BigDecimal) {
    this.set("amountIn", Value.fromBigDecimal(value));
  }

  get amountOut(): BigDecimal {
    let value = this.get("amountOut");
    return value.toBigDecimal();
  }

  set amountOut(value: BigDecimal) {
    this.set("amountOut", Value.fromBigDecimal(value));
  }

  get amountUSDC(): BigDecimal {
    let value = this.get("amountUSDC");
    return value.toBigDecimal();
  }

  set amountUSDC(value: BigDecimal) {
    this.set("amountUSDC", Value.fromBigDecimal(value));
  }
}

export class FlashLoan extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save FlashLoan entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save FlashLoan entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("FlashLoan", id.toString(), this);
  }

  static load(id: string): FlashLoan | null {
    return store.get("FlashLoan", id) as FlashLoan | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get hash(): string {
    let value = this.get("hash");
    return value.toString();
  }

  set hash(value: string) {
    this.set("hash", Value.fromString(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }

  get pair(): string {
    let value = this.get("pair");
    return value.toString();
  }

  set pair(value: string) {
    this.set("pair", Value.fromString(value));
  }

  get sender(): Bytes {
    let value = this.get("sender");
    return value.toBytes();
  }

  set sender(value: Bytes) {
    this.set("sender", Value.fromBytes(value));
  }

  get from(): Bytes {
    let value = this.get("from");
    return value.toBytes();
  }

  set from(value: Bytes) {
    this.set("from", Value.fromBytes(value));
  }

  get baseAmount(): BigDecimal {
    let value = this.get("baseAmount");
    return value.toBigDecimal();
  }

  set baseAmount(value: BigDecimal) {
    this.set("baseAmount", Value.fromBigDecimal(value));
  }

  get quoteAmount(): BigDecimal {
    let value = this.get("quoteAmount");
    return value.toBigDecimal();
  }

  set quoteAmount(value: BigDecimal) {
    this.set("quoteAmount", Value.fromBigDecimal(value));
  }
}

export class PairDayData extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save PairDayData entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save PairDayData entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("PairDayData", id.toString(), this);
  }

  static load(id: string): PairDayData | null {
    return store.get("PairDayData", id) as PairDayData | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get date(): i32 {
    let value = this.get("date");
    return value.toI32();
  }

  set date(value: i32) {
    this.set("date", Value.fromI32(value));
  }

  get pairAddress(): Bytes {
    let value = this.get("pairAddress");
    return value.toBytes();
  }

  set pairAddress(value: Bytes) {
    this.set("pairAddress", Value.fromBytes(value));
  }

  get baseToken(): string {
    let value = this.get("baseToken");
    return value.toString();
  }

  set baseToken(value: string) {
    this.set("baseToken", Value.fromString(value));
  }

  get quoteToken(): string {
    let value = this.get("quoteToken");
    return value.toString();
  }

  set quoteToken(value: string) {
    this.set("quoteToken", Value.fromString(value));
  }

  get baseTokenReserve(): BigDecimal {
    let value = this.get("baseTokenReserve");
    return value.toBigDecimal();
  }

  set baseTokenReserve(value: BigDecimal) {
    this.set("baseTokenReserve", Value.fromBigDecimal(value));
  }

  get quoteTokenReserve(): BigDecimal {
    let value = this.get("quoteTokenReserve");
    return value.toBigDecimal();
  }

  set quoteTokenReserve(value: BigDecimal) {
    this.set("quoteTokenReserve", Value.fromBigDecimal(value));
  }

  get baseLpTokenTotalSupply(): BigDecimal {
    let value = this.get("baseLpTokenTotalSupply");
    return value.toBigDecimal();
  }

  set baseLpTokenTotalSupply(value: BigDecimal) {
    this.set("baseLpTokenTotalSupply", Value.fromBigDecimal(value));
  }

  get quoteLpTokenTotalSupply(): BigDecimal {
    let value = this.get("quoteLpTokenTotalSupply");
    return value.toBigDecimal();
  }

  set quoteLpTokenTotalSupply(value: BigDecimal) {
    this.set("quoteLpTokenTotalSupply", Value.fromBigDecimal(value));
  }

  get reserveUSDC(): BigDecimal {
    let value = this.get("reserveUSDC");
    return value.toBigDecimal();
  }

  set reserveUSDC(value: BigDecimal) {
    this.set("reserveUSDC", Value.fromBigDecimal(value));
  }

  get dailyVolumeBase(): BigDecimal {
    let value = this.get("dailyVolumeBase");
    return value.toBigDecimal();
  }

  set dailyVolumeBase(value: BigDecimal) {
    this.set("dailyVolumeBase", Value.fromBigDecimal(value));
  }

  get dailyVolumeQuote(): BigDecimal {
    let value = this.get("dailyVolumeQuote");
    return value.toBigDecimal();
  }

  set dailyVolumeQuote(value: BigDecimal) {
    this.set("dailyVolumeQuote", Value.fromBigDecimal(value));
  }

  get dailyVolumeUSDC(): BigDecimal {
    let value = this.get("dailyVolumeUSDC");
    return value.toBigDecimal();
  }

  set dailyVolumeUSDC(value: BigDecimal) {
    this.set("dailyVolumeUSDC", Value.fromBigDecimal(value));
  }

  get dailyTxns(): BigInt {
    let value = this.get("dailyTxns");
    return value.toBigInt();
  }

  set dailyTxns(value: BigInt) {
    this.set("dailyTxns", Value.fromBigInt(value));
  }

  get fee(): BigDecimal {
    let value = this.get("fee");
    return value.toBigDecimal();
  }

  set fee(value: BigDecimal) {
    this.set("fee", Value.fromBigDecimal(value));
  }
}

export class TokenDayData extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save TokenDayData entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save TokenDayData entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("TokenDayData", id.toString(), this);
  }

  static load(id: string): TokenDayData | null {
    return store.get("TokenDayData", id) as TokenDayData | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get date(): i32 {
    let value = this.get("date");
    return value.toI32();
  }

  set date(value: i32) {
    this.set("date", Value.fromI32(value));
  }

  get token(): string {
    let value = this.get("token");
    return value.toString();
  }

  set token(value: string) {
    this.set("token", Value.fromString(value));
  }

  get dailyVolumeToken(): BigDecimal {
    let value = this.get("dailyVolumeToken");
    return value.toBigDecimal();
  }

  set dailyVolumeToken(value: BigDecimal) {
    this.set("dailyVolumeToken", Value.fromBigDecimal(value));
  }

  get dailyVolumeUSDC(): BigDecimal {
    let value = this.get("dailyVolumeUSDC");
    return value.toBigDecimal();
  }

  set dailyVolumeUSDC(value: BigDecimal) {
    this.set("dailyVolumeUSDC", Value.fromBigDecimal(value));
  }

  get dailyTxns(): BigInt {
    let value = this.get("dailyTxns");
    return value.toBigInt();
  }

  set dailyTxns(value: BigInt) {
    this.set("dailyTxns", Value.fromBigInt(value));
  }

  get totalLiquidityToken(): BigDecimal {
    let value = this.get("totalLiquidityToken");
    return value.toBigDecimal();
  }

  set totalLiquidityToken(value: BigDecimal) {
    this.set("totalLiquidityToken", Value.fromBigDecimal(value));
  }

  get totalLiquidityUSDC(): BigDecimal {
    let value = this.get("totalLiquidityUSDC");
    return value.toBigDecimal();
  }

  set totalLiquidityUSDC(value: BigDecimal) {
    this.set("totalLiquidityUSDC", Value.fromBigDecimal(value));
  }

  get priceUSDC(): BigDecimal {
    let value = this.get("priceUSDC");
    return value.toBigDecimal();
  }

  set priceUSDC(value: BigDecimal) {
    this.set("priceUSDC", Value.fromBigDecimal(value));
  }

  get fee(): BigDecimal {
    let value = this.get("fee");
    return value.toBigDecimal();
  }

  set fee(value: BigDecimal) {
    this.set("fee", Value.fromBigDecimal(value));
  }
}

export class CrowdPooling extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save CrowdPooling entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save CrowdPooling entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("CrowdPooling", id.toString(), this);
  }

  static load(id: string): CrowdPooling | null {
    return store.get("CrowdPooling", id) as CrowdPooling | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get creator(): Bytes {
    let value = this.get("creator");
    return value.toBytes();
  }

  set creator(value: Bytes) {
    this.set("creator", Value.fromBytes(value));
  }

  get baseToken(): string {
    let value = this.get("baseToken");
    return value.toString();
  }

  set baseToken(value: string) {
    this.set("baseToken", Value.fromString(value));
  }

  get quoteToken(): string {
    let value = this.get("quoteToken");
    return value.toString();
  }

  set quoteToken(value: string) {
    this.set("quoteToken", Value.fromString(value));
  }

  get bidStartTime(): BigInt {
    let value = this.get("bidStartTime");
    return value.toBigInt();
  }

  set bidStartTime(value: BigInt) {
    this.set("bidStartTime", Value.fromBigInt(value));
  }

  get bidEndTime(): BigInt {
    let value = this.get("bidEndTime");
    return value.toBigInt();
  }

  set bidEndTime(value: BigInt) {
    this.set("bidEndTime", Value.fromBigInt(value));
  }

  get calmEndTime(): BigInt {
    let value = this.get("calmEndTime");
    return value.toBigInt();
  }

  set calmEndTime(value: BigInt) {
    this.set("calmEndTime", Value.fromBigInt(value));
  }

  get freezeDuration(): BigInt {
    let value = this.get("freezeDuration");
    return value.toBigInt();
  }

  set freezeDuration(value: BigInt) {
    this.set("freezeDuration", Value.fromBigInt(value));
  }

  get vestingDuration(): BigInt {
    let value = this.get("vestingDuration");
    return value.toBigInt();
  }

  set vestingDuration(value: BigInt) {
    this.set("vestingDuration", Value.fromBigInt(value));
  }

  get i(): BigInt {
    let value = this.get("i");
    return value.toBigInt();
  }

  set i(value: BigInt) {
    this.set("i", Value.fromBigInt(value));
  }

  get k(): BigInt {
    let value = this.get("k");
    return value.toBigInt();
  }

  set k(value: BigInt) {
    this.set("k", Value.fromBigInt(value));
  }

  get totalBase(): BigDecimal {
    let value = this.get("totalBase");
    return value.toBigDecimal();
  }

  set totalBase(value: BigDecimal) {
    this.set("totalBase", Value.fromBigDecimal(value));
  }

  get settled(): boolean {
    let value = this.get("settled");
    return value.toBoolean();
  }

  set settled(value: boolean) {
    this.set("settled", Value.fromBoolean(value));
  }

  get poolQuote(): BigDecimal {
    let value = this.get("poolQuote");
    return value.toBigDecimal();
  }

  set poolQuote(value: BigDecimal) {
    this.set("poolQuote", Value.fromBigDecimal(value));
  }

  get poolQuoteCap(): BigDecimal {
    let value = this.get("poolQuoteCap");
    return value.toBigDecimal();
  }

  set poolQuoteCap(value: BigDecimal) {
    this.set("poolQuoteCap", Value.fromBigDecimal(value));
  }

  get investorsCount(): BigInt {
    let value = this.get("investorsCount");
    return value.toBigInt();
  }

  set investorsCount(value: BigInt) {
    this.set("investorsCount", Value.fromBigInt(value));
  }
}

export class BidPosition extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save BidPosition entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save BidPosition entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("BidPosition", id.toString(), this);
  }

  static load(id: string): BidPosition | null {
    return store.get("BidPosition", id) as BidPosition | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get user(): string {
    let value = this.get("user");
    return value.toString();
  }

  set user(value: string) {
    this.set("user", Value.fromString(value));
  }

  get cp(): string {
    let value = this.get("cp");
    return value.toString();
  }

  set cp(value: string) {
    this.set("cp", Value.fromString(value));
  }

  get shares(): BigDecimal {
    let value = this.get("shares");
    return value.toBigDecimal();
  }

  set shares(value: BigDecimal) {
    this.set("shares", Value.fromBigDecimal(value));
  }

  get investedQuote(): BigDecimal {
    let value = this.get("investedQuote");
    return value.toBigDecimal();
  }

  set investedQuote(value: BigDecimal) {
    this.set("investedQuote", Value.fromBigDecimal(value));
  }
}

export class BidHistory extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save BidHistory entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save BidHistory entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("BidHistory", id.toString(), this);
  }

  static load(id: string): BidHistory | null {
    return store.get("BidHistory", id) as BidHistory | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get user(): string {
    let value = this.get("user");
    return value.toString();
  }

  set user(value: string) {
    this.set("user", Value.fromString(value));
  }

  get cp(): string {
    let value = this.get("cp");
    return value.toString();
  }

  set cp(value: string) {
    this.set("cp", Value.fromString(value));
  }

  get action(): string {
    let value = this.get("action");
    return value.toString();
  }

  set action(value: string) {
    this.set("action", Value.fromString(value));
  }

  get hash(): string {
    let value = this.get("hash");
    return value.toString();
  }

  set hash(value: string) {
    this.set("hash", Value.fromString(value));
  }

  get block(): BigInt {
    let value = this.get("block");
    return value.toBigInt();
  }

  set block(value: BigInt) {
    this.set("block", Value.fromBigInt(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }

  get quote(): BigDecimal {
    let value = this.get("quote");
    return value.toBigDecimal();
  }

  set quote(value: BigDecimal) {
    this.set("quote", Value.fromBigDecimal(value));
  }

  get share(): BigDecimal {
    let value = this.get("share");
    return value.toBigDecimal();
  }

  set share(value: BigDecimal) {
    this.set("share", Value.fromBigDecimal(value));
  }
}

export class CrowdPoolingDayData extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save CrowdPoolingDayData entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save CrowdPoolingDayData entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("CrowdPoolingDayData", id.toString(), this);
  }

  static load(id: string): CrowdPoolingDayData | null {
    return store.get("CrowdPoolingDayData", id) as CrowdPoolingDayData | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get date(): i32 {
    let value = this.get("date");
    return value.toI32();
  }

  set date(value: i32) {
    this.set("date", Value.fromI32(value));
  }

  get crowdPooling(): string {
    let value = this.get("crowdPooling");
    return value.toString();
  }

  set crowdPooling(value: string) {
    this.set("crowdPooling", Value.fromString(value));
  }

  get investedQuote(): BigDecimal {
    let value = this.get("investedQuote");
    return value.toBigDecimal();
  }

  set investedQuote(value: BigDecimal) {
    this.set("investedQuote", Value.fromBigDecimal(value));
  }

  get canceledQuote(): BigDecimal {
    let value = this.get("canceledQuote");
    return value.toBigDecimal();
  }

  set canceledQuote(value: BigDecimal) {
    this.set("canceledQuote", Value.fromBigDecimal(value));
  }

  get investCount(): BigInt {
    let value = this.get("investCount");
    return value.toBigInt();
  }

  set investCount(value: BigInt) {
    this.set("investCount", Value.fromBigInt(value));
  }

  get newcome(): BigInt {
    let value = this.get("newcome");
    return value.toBigInt();
  }

  set newcome(value: BigInt) {
    this.set("newcome", Value.fromBigInt(value));
  }

  get poolQuote(): BigDecimal {
    let value = this.get("poolQuote");
    return value.toBigDecimal();
  }

  set poolQuote(value: BigDecimal) {
    this.set("poolQuote", Value.fromBigDecimal(value));
  }
}

export class IncentiveRewardReceived extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(
      id !== null,
      "Cannot save IncentiveRewardReceived entity without an ID"
    );
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save IncentiveRewardReceived entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("IncentiveRewardReceived", id.toString(), this);
  }

  static load(id: string): IncentiveRewardReceived | null {
    return store.get(
      "IncentiveRewardReceived",
      id
    ) as IncentiveRewardReceived | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get amount(): BigDecimal {
    let value = this.get("amount");
    return value.toBigDecimal();
  }

  set amount(value: BigDecimal) {
    this.set("amount", Value.fromBigDecimal(value));
  }
}

export class IncentiveRewardHistory extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(
      id !== null,
      "Cannot save IncentiveRewardHistory entity without an ID"
    );
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save IncentiveRewardHistory entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("IncentiveRewardHistory", id.toString(), this);
  }

  static load(id: string): IncentiveRewardHistory | null {
    return store.get(
      "IncentiveRewardHistory",
      id
    ) as IncentiveRewardHistory | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get user(): string {
    let value = this.get("user");
    return value.toString();
  }

  set user(value: string) {
    this.set("user", Value.fromString(value));
  }

  get amount(): BigDecimal {
    let value = this.get("amount");
    return value.toBigDecimal();
  }

  set amount(value: BigDecimal) {
    this.set("amount", Value.fromBigDecimal(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }

  get totalAmount(): BigDecimal {
    let value = this.get("totalAmount");
    return value.toBigDecimal();
  }

  set totalAmount(value: BigDecimal) {
    this.set("totalAmount", Value.fromBigDecimal(value));
  }

  get totalUser(): BigInt {
    let value = this.get("totalUser");
    return value.toBigInt();
  }

  set totalUser(value: BigInt) {
    this.set("totalUser", Value.fromBigInt(value));
  }
}
