// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class NewCP extends ethereum.Event {
  get params(): NewCP__Params {
    return new NewCP__Params(this);
  }
}

export class NewCP__Params {
  _event: NewCP;

  constructor(event: NewCP) {
    this._event = event;
  }

  get baseToken(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get quoteToken(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get creator(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get cp(): Address {
    return this._event.parameters[3].value.toAddress();
  }
}

export class OwnershipTransferPrepared extends ethereum.Event {
  get params(): OwnershipTransferPrepared__Params {
    return new OwnershipTransferPrepared__Params(this);
  }
}

export class OwnershipTransferPrepared__Params {
  _event: OwnershipTransferPrepared;

  constructor(event: OwnershipTransferPrepared) {
    this._event = event;
  }

  get previousOwner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get newOwner(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class OwnershipTransferred extends ethereum.Event {
  get params(): OwnershipTransferred__Params {
    return new OwnershipTransferred__Params(this);
  }
}

export class OwnershipTransferred__Params {
  _event: OwnershipTransferred;

  constructor(event: OwnershipTransferred) {
    this._event = event;
  }

  get previousOwner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get newOwner(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class CrowdPoolingFactory__getCrowdPoolingBidirectionResult {
  value0: Array<Address>;
  value1: Array<Address>;

  constructor(value0: Array<Address>, value1: Array<Address>) {
    this.value0 = value0;
    this.value1 = value1;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromAddressArray(this.value0));
    map.set("value1", ethereum.Value.fromAddressArray(this.value1));
    return map;
  }
}

export class CrowdPoolingFactory extends ethereum.SmartContract {
  static bind(address: Address): CrowdPoolingFactory {
    return new CrowdPoolingFactory("CrowdPoolingFactory", address);
  }

  _CALM_DURATION_(): BigInt {
    let result = super.call(
      "_CALM_DURATION_",
      "_CALM_DURATION_():(uint256)",
      []
    );

    return result[0].toBigInt();
  }

  try__CALM_DURATION_(): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "_CALM_DURATION_",
      "_CALM_DURATION_():(uint256)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  _CAP_RATIO_(): BigInt {
    let result = super.call("_CAP_RATIO_", "_CAP_RATIO_():(uint256)", []);

    return result[0].toBigInt();
  }

  try__CAP_RATIO_(): ethereum.CallResult<BigInt> {
    let result = super.tryCall("_CAP_RATIO_", "_CAP_RATIO_():(uint256)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  _CLIFF_RATE_(): BigInt {
    let result = super.call("_CLIFF_RATE_", "_CLIFF_RATE_():(uint256)", []);

    return result[0].toBigInt();
  }

  try__CLIFF_RATE_(): ethereum.CallResult<BigInt> {
    let result = super.tryCall("_CLIFF_RATE_", "_CLIFF_RATE_():(uint256)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  _CLONE_FACTORY_(): Address {
    let result = super.call(
      "_CLONE_FACTORY_",
      "_CLONE_FACTORY_():(address)",
      []
    );

    return result[0].toAddress();
  }

  try__CLONE_FACTORY_(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "_CLONE_FACTORY_",
      "_CLONE_FACTORY_():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  _CP_TEMPLATE_(): Address {
    let result = super.call("_CP_TEMPLATE_", "_CP_TEMPLATE_():(address)", []);

    return result[0].toAddress();
  }

  try__CP_TEMPLATE_(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "_CP_TEMPLATE_",
      "_CP_TEMPLATE_():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  _DEFAULT_MAINTAINER_(): Address {
    let result = super.call(
      "_DEFAULT_MAINTAINER_",
      "_DEFAULT_MAINTAINER_():(address)",
      []
    );

    return result[0].toAddress();
  }

  try__DEFAULT_MAINTAINER_(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "_DEFAULT_MAINTAINER_",
      "_DEFAULT_MAINTAINER_():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  _DEFAULT_MT_FEE_RATE_MODEL_(): Address {
    let result = super.call(
      "_DEFAULT_MT_FEE_RATE_MODEL_",
      "_DEFAULT_MT_FEE_RATE_MODEL_():(address)",
      []
    );

    return result[0].toAddress();
  }

  try__DEFAULT_MT_FEE_RATE_MODEL_(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "_DEFAULT_MT_FEE_RATE_MODEL_",
      "_DEFAULT_MT_FEE_RATE_MODEL_():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  _DEFAULT_PERMISSION_MANAGER_(): Address {
    let result = super.call(
      "_DEFAULT_PERMISSION_MANAGER_",
      "_DEFAULT_PERMISSION_MANAGER_():(address)",
      []
    );

    return result[0].toAddress();
  }

  try__DEFAULT_PERMISSION_MANAGER_(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "_DEFAULT_PERMISSION_MANAGER_",
      "_DEFAULT_PERMISSION_MANAGER_():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  _DVM_FACTORY_(): Address {
    let result = super.call("_DVM_FACTORY_", "_DVM_FACTORY_():(address)", []);

    return result[0].toAddress();
  }

  try__DVM_FACTORY_(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "_DVM_FACTORY_",
      "_DVM_FACTORY_():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  _FREEZE_DURATION_(): BigInt {
    let result = super.call(
      "_FREEZE_DURATION_",
      "_FREEZE_DURATION_():(uint256)",
      []
    );

    return result[0].toBigInt();
  }

  try__FREEZE_DURATION_(): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "_FREEZE_DURATION_",
      "_FREEZE_DURATION_():(uint256)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  _K_(): BigInt {
    let result = super.call("_K_", "_K_():(uint256)", []);

    return result[0].toBigInt();
  }

  try__K_(): ethereum.CallResult<BigInt> {
    let result = super.tryCall("_K_", "_K_():(uint256)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  _NEW_OWNER_(): Address {
    let result = super.call("_NEW_OWNER_", "_NEW_OWNER_():(address)", []);

    return result[0].toAddress();
  }

  try__NEW_OWNER_(): ethereum.CallResult<Address> {
    let result = super.tryCall("_NEW_OWNER_", "_NEW_OWNER_():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  _OWNER_(): Address {
    let result = super.call("_OWNER_", "_OWNER_():(address)", []);

    return result[0].toAddress();
  }

  try__OWNER_(): ethereum.CallResult<Address> {
    let result = super.tryCall("_OWNER_", "_OWNER_():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  _REGISTRY_(param0: Address, param1: Address, param2: BigInt): Address {
    let result = super.call(
      "_REGISTRY_",
      "_REGISTRY_(address,address,uint256):(address)",
      [
        ethereum.Value.fromAddress(param0),
        ethereum.Value.fromAddress(param1),
        ethereum.Value.fromUnsignedBigInt(param2)
      ]
    );

    return result[0].toAddress();
  }

  try__REGISTRY_(
    param0: Address,
    param1: Address,
    param2: BigInt
  ): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "_REGISTRY_",
      "_REGISTRY_(address,address,uint256):(address)",
      [
        ethereum.Value.fromAddress(param0),
        ethereum.Value.fromAddress(param1),
        ethereum.Value.fromUnsignedBigInt(param2)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  _USER_REGISTRY_(param0: Address, param1: BigInt): Address {
    let result = super.call(
      "_USER_REGISTRY_",
      "_USER_REGISTRY_(address,uint256):(address)",
      [
        ethereum.Value.fromAddress(param0),
        ethereum.Value.fromUnsignedBigInt(param1)
      ]
    );

    return result[0].toAddress();
  }

  try__USER_REGISTRY_(
    param0: Address,
    param1: BigInt
  ): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "_USER_REGISTRY_",
      "_USER_REGISTRY_(address,uint256):(address)",
      [
        ethereum.Value.fromAddress(param0),
        ethereum.Value.fromUnsignedBigInt(param1)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  _VEST_DURATION_(): BigInt {
    let result = super.call(
      "_VEST_DURATION_",
      "_VEST_DURATION_():(uint256)",
      []
    );

    return result[0].toBigInt();
  }

  try__VEST_DURATION_(): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "_VEST_DURATION_",
      "_VEST_DURATION_():(uint256)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  createCrowdPooling(): Address {
    let result = super.call(
      "createCrowdPooling",
      "createCrowdPooling():(address)",
      []
    );

    return result[0].toAddress();
  }

  try_createCrowdPooling(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "createCrowdPooling",
      "createCrowdPooling():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getCrowdPooling(baseToken: Address, quoteToken: Address): Array<Address> {
    let result = super.call(
      "getCrowdPooling",
      "getCrowdPooling(address,address):(address[])",
      [
        ethereum.Value.fromAddress(baseToken),
        ethereum.Value.fromAddress(quoteToken)
      ]
    );

    return result[0].toAddressArray();
  }

  try_getCrowdPooling(
    baseToken: Address,
    quoteToken: Address
  ): ethereum.CallResult<Array<Address>> {
    let result = super.tryCall(
      "getCrowdPooling",
      "getCrowdPooling(address,address):(address[])",
      [
        ethereum.Value.fromAddress(baseToken),
        ethereum.Value.fromAddress(quoteToken)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddressArray());
  }

  getCrowdPoolingBidirection(
    token0: Address,
    token1: Address
  ): CrowdPoolingFactory__getCrowdPoolingBidirectionResult {
    let result = super.call(
      "getCrowdPoolingBidirection",
      "getCrowdPoolingBidirection(address,address):(address[],address[])",
      [ethereum.Value.fromAddress(token0), ethereum.Value.fromAddress(token1)]
    );

    return new CrowdPoolingFactory__getCrowdPoolingBidirectionResult(
      result[0].toAddressArray(),
      result[1].toAddressArray()
    );
  }

  try_getCrowdPoolingBidirection(
    token0: Address,
    token1: Address
  ): ethereum.CallResult<
    CrowdPoolingFactory__getCrowdPoolingBidirectionResult
  > {
    let result = super.tryCall(
      "getCrowdPoolingBidirection",
      "getCrowdPoolingBidirection(address,address):(address[],address[])",
      [ethereum.Value.fromAddress(token0), ethereum.Value.fromAddress(token1)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new CrowdPoolingFactory__getCrowdPoolingBidirectionResult(
        value[0].toAddressArray(),
        value[1].toAddressArray()
      )
    );
  }

  getCrowdPoolingByUser(user: Address): Array<Address> {
    let result = super.call(
      "getCrowdPoolingByUser",
      "getCrowdPoolingByUser(address):(address[])",
      [ethereum.Value.fromAddress(user)]
    );

    return result[0].toAddressArray();
  }

  try_getCrowdPoolingByUser(
    user: Address
  ): ethereum.CallResult<Array<Address>> {
    let result = super.tryCall(
      "getCrowdPoolingByUser",
      "getCrowdPoolingByUser(address):(address[])",
      [ethereum.Value.fromAddress(user)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddressArray());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }

  get cloneFactory(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get cpTemplate(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get dvmFactory(): Address {
    return this._call.inputValues[2].value.toAddress();
  }

  get defaultMaintainer(): Address {
    return this._call.inputValues[3].value.toAddress();
  }

  get defaultMtFeeRateModel(): Address {
    return this._call.inputValues[4].value.toAddress();
  }

  get defaultPermissionManager(): Address {
    return this._call.inputValues[5].value.toAddress();
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class ClaimOwnershipCall extends ethereum.Call {
  get inputs(): ClaimOwnershipCall__Inputs {
    return new ClaimOwnershipCall__Inputs(this);
  }

  get outputs(): ClaimOwnershipCall__Outputs {
    return new ClaimOwnershipCall__Outputs(this);
  }
}

export class ClaimOwnershipCall__Inputs {
  _call: ClaimOwnershipCall;

  constructor(call: ClaimOwnershipCall) {
    this._call = call;
  }
}

export class ClaimOwnershipCall__Outputs {
  _call: ClaimOwnershipCall;

  constructor(call: ClaimOwnershipCall) {
    this._call = call;
  }
}

export class InitOwnerCall extends ethereum.Call {
  get inputs(): InitOwnerCall__Inputs {
    return new InitOwnerCall__Inputs(this);
  }

  get outputs(): InitOwnerCall__Outputs {
    return new InitOwnerCall__Outputs(this);
  }
}

export class InitOwnerCall__Inputs {
  _call: InitOwnerCall;

  constructor(call: InitOwnerCall) {
    this._call = call;
  }

  get newOwner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class InitOwnerCall__Outputs {
  _call: InitOwnerCall;

  constructor(call: InitOwnerCall) {
    this._call = call;
  }
}

export class TransferOwnershipCall extends ethereum.Call {
  get inputs(): TransferOwnershipCall__Inputs {
    return new TransferOwnershipCall__Inputs(this);
  }

  get outputs(): TransferOwnershipCall__Outputs {
    return new TransferOwnershipCall__Outputs(this);
  }
}

export class TransferOwnershipCall__Inputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }

  get newOwner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class TransferOwnershipCall__Outputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }
}

export class CreateCrowdPoolingCall extends ethereum.Call {
  get inputs(): CreateCrowdPoolingCall__Inputs {
    return new CreateCrowdPoolingCall__Inputs(this);
  }

  get outputs(): CreateCrowdPoolingCall__Outputs {
    return new CreateCrowdPoolingCall__Outputs(this);
  }
}

export class CreateCrowdPoolingCall__Inputs {
  _call: CreateCrowdPoolingCall;

  constructor(call: CreateCrowdPoolingCall) {
    this._call = call;
  }
}

export class CreateCrowdPoolingCall__Outputs {
  _call: CreateCrowdPoolingCall;

  constructor(call: CreateCrowdPoolingCall) {
    this._call = call;
  }

  get newCrowdPooling(): Address {
    return this._call.outputValues[0].value.toAddress();
  }
}

export class InitCrowdPoolingCall extends ethereum.Call {
  get inputs(): InitCrowdPoolingCall__Inputs {
    return new InitCrowdPoolingCall__Inputs(this);
  }

  get outputs(): InitCrowdPoolingCall__Outputs {
    return new InitCrowdPoolingCall__Outputs(this);
  }
}

export class InitCrowdPoolingCall__Inputs {
  _call: InitCrowdPoolingCall;

  constructor(call: InitCrowdPoolingCall) {
    this._call = call;
  }

  get cpAddress(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get creator(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get baseToken(): Address {
    return this._call.inputValues[2].value.toAddress();
  }

  get quoteToken(): Address {
    return this._call.inputValues[3].value.toAddress();
  }

  get timeLine(): Array<BigInt> {
    return this._call.inputValues[4].value.toBigIntArray();
  }

  get valueList(): Array<BigInt> {
    return this._call.inputValues[5].value.toBigIntArray();
  }
}

export class InitCrowdPoolingCall__Outputs {
  _call: InitCrowdPoolingCall;

  constructor(call: InitCrowdPoolingCall) {
    this._call = call;
  }
}

export class UpdateCPTemplateCall extends ethereum.Call {
  get inputs(): UpdateCPTemplateCall__Inputs {
    return new UpdateCPTemplateCall__Inputs(this);
  }

  get outputs(): UpdateCPTemplateCall__Outputs {
    return new UpdateCPTemplateCall__Outputs(this);
  }
}

export class UpdateCPTemplateCall__Inputs {
  _call: UpdateCPTemplateCall;

  constructor(call: UpdateCPTemplateCall) {
    this._call = call;
  }

  get _newCPTemplate(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class UpdateCPTemplateCall__Outputs {
  _call: UpdateCPTemplateCall;

  constructor(call: UpdateCPTemplateCall) {
    this._call = call;
  }
}

export class SetCapRatioCall extends ethereum.Call {
  get inputs(): SetCapRatioCall__Inputs {
    return new SetCapRatioCall__Inputs(this);
  }

  get outputs(): SetCapRatioCall__Outputs {
    return new SetCapRatioCall__Outputs(this);
  }
}

export class SetCapRatioCall__Inputs {
  _call: SetCapRatioCall;

  constructor(call: SetCapRatioCall) {
    this._call = call;
  }

  get _newCapRatio(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class SetCapRatioCall__Outputs {
  _call: SetCapRatioCall;

  constructor(call: SetCapRatioCall) {
    this._call = call;
  }
}

export class SetFreezeDurationCall extends ethereum.Call {
  get inputs(): SetFreezeDurationCall__Inputs {
    return new SetFreezeDurationCall__Inputs(this);
  }

  get outputs(): SetFreezeDurationCall__Outputs {
    return new SetFreezeDurationCall__Outputs(this);
  }
}

export class SetFreezeDurationCall__Inputs {
  _call: SetFreezeDurationCall;

  constructor(call: SetFreezeDurationCall) {
    this._call = call;
  }

  get _newFreeDuration(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class SetFreezeDurationCall__Outputs {
  _call: SetFreezeDurationCall;

  constructor(call: SetFreezeDurationCall) {
    this._call = call;
  }
}

export class SetCalmDurationCall extends ethereum.Call {
  get inputs(): SetCalmDurationCall__Inputs {
    return new SetCalmDurationCall__Inputs(this);
  }

  get outputs(): SetCalmDurationCall__Outputs {
    return new SetCalmDurationCall__Outputs(this);
  }
}

export class SetCalmDurationCall__Inputs {
  _call: SetCalmDurationCall;

  constructor(call: SetCalmDurationCall) {
    this._call = call;
  }

  get _newCalmDuration(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class SetCalmDurationCall__Outputs {
  _call: SetCalmDurationCall;

  constructor(call: SetCalmDurationCall) {
    this._call = call;
  }
}

export class SetVestDurationCall extends ethereum.Call {
  get inputs(): SetVestDurationCall__Inputs {
    return new SetVestDurationCall__Inputs(this);
  }

  get outputs(): SetVestDurationCall__Outputs {
    return new SetVestDurationCall__Outputs(this);
  }
}

export class SetVestDurationCall__Inputs {
  _call: SetVestDurationCall;

  constructor(call: SetVestDurationCall) {
    this._call = call;
  }

  get _newVestDuration(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class SetVestDurationCall__Outputs {
  _call: SetVestDurationCall;

  constructor(call: SetVestDurationCall) {
    this._call = call;
  }
}

export class SetKCall extends ethereum.Call {
  get inputs(): SetKCall__Inputs {
    return new SetKCall__Inputs(this);
  }

  get outputs(): SetKCall__Outputs {
    return new SetKCall__Outputs(this);
  }
}

export class SetKCall__Inputs {
  _call: SetKCall;

  constructor(call: SetKCall) {
    this._call = call;
  }

  get _newK(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class SetKCall__Outputs {
  _call: SetKCall;

  constructor(call: SetKCall) {
    this._call = call;
  }
}

export class SetCliffRateCall extends ethereum.Call {
  get inputs(): SetCliffRateCall__Inputs {
    return new SetCliffRateCall__Inputs(this);
  }

  get outputs(): SetCliffRateCall__Outputs {
    return new SetCliffRateCall__Outputs(this);
  }
}

export class SetCliffRateCall__Inputs {
  _call: SetCliffRateCall;

  constructor(call: SetCliffRateCall) {
    this._call = call;
  }

  get _newCliffRate(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class SetCliffRateCall__Outputs {
  _call: SetCliffRateCall;

  constructor(call: SetCliffRateCall) {
    this._call = call;
  }
}
